### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by wolfier74** [FlaringPhoenix/Ptero-Status#1]
How to use this? Where should i add example usage from readme.md ?
Should I create hosting server on pterodactyl in every node and paste there this?
```
const Status = require('pterostatus');

const Daemon = new Status.Daemon("Node1", 15000, {
    ip: "PANEL-IP",
    port: "PANEL-PORT"
});
```

**Comment by FlaringPhoenix** [comment]
So basically you need to add that snippet of code to every single pterodactyl node and properly configure the PANEL-IP and the PANEL-PORT.

You will need to run:
```
const Status = require('pterostatus');

const Panel = new Status.Panel(4000, {
    token: "BOT-TOKEN",
    guildID: 'GUILD-ID',
    channelID: 'CHANNEL-ID',
    color: '#06cce2', // Embed color
    interval: 15000
});
```

on a pterodactyl server as well. The ip and port of the "Panel" server is what you will put in the daemon PANEL-IP and PANEL-PORT.

**Comment by wolfier74** [comment]
Thanks
