### ISSUE TITLE
How to use 2 nodes?

### ISSUE THREAD

**Issue by HirziDevs** [FlaringPhoenix/Ptero-Status#10]
How i create the status with 2 nodes or more?

**Comment by protoxz** [comment]
> How i create the status with 2 nodes or more?

Did you find ? Im trying too :(

**Comment by SuperS123** [comment]
> How i create the status with 2 nodes or more?

I think you can just do
```js
const node1 = new Status.Daemon('Node1', 15000, {
    ip: 'CONTROLLER-IP',
    port: 'CONTROLLER-PORT'
});

const node2 = new Status.Daemon('Node2', 15000, {
    ip: 'CONTROLLER-IP',
    port: 'CONTROLLER-PORT'
});
```

**Comment by protoxz** [comment]
> > How i create the status with 2 nodes or more?
> 
> I think you can just do
> 
> ```js
> const node1 = new Status.Daemon('Node1', 15000, {
>     ip: 'CONTROLLER-IP',
>     port: 'CONTROLLER-PORT'
> });
> 
> const node2 = new Status.Daemon('Node2', 15000, {
>     ip: 'CONTROLLER-IP',
>     port: 'CONTROLLER-PORT'
> });
> ```

Hi, thanks, when i put a second one, i have this error and message on discord dont update :

http://puu.sh/HpWOk/c7c8d4352f.png

**Comment by HirziDevs** [comment]
> > > How i create the status with 2 nodes or more?
> > 
> > 
> > I think you can just do
> > ```js
> > const node1 = new Status.Daemon('Node1', 15000, {
> >     ip: 'CONTROLLER-IP',
> >     port: 'CONTROLLER-PORT'
> > });
> > 
> > const node2 = new Status.Daemon('Node2', 15000, {
> >     ip: 'CONTROLLER-IP',
> >     port: 'CONTROLLER-PORT'
> > });
> > ```
> 
> Hi, thanks, when i put a second one, i have this error and message on discord dont update :
> 
> http://puu.sh/HpWOk/c7c8d4352f.png

for me its "failed to post the stats"

**Comment by FlaringPhoenix** [comment]
It appears that you are using an outdated version of PteroStatus, please update. 

Also you can't just add this to the same file:
```js
const node1 = new Status.Daemon('Node1', 15000, {
    ip: 'CONTROLLER-IP',
    port: 'CONTROLLER-PORT'
});

const node2 = new Status.Daemon('Node2', 15000, {
    ip: 'CONTROLLER-IP',
    port: 'CONTROLLER-PORT'
});
```


You need to put this on each separate node: [click-here](https://haste.bluefoxhost.com/ecagi.php)

**Comment by BranGamer145** [comment]
> It appears that you are using an outdated version of PteroStatus, please update.
> 
> Also you can't just add this to the same file:
> 
> ```js
> const node1 = new Status.Daemon('Node1', 15000, {
>     ip: 'CONTROLLER-IP',
>     port: 'CONTROLLER-PORT'
> });
> 
> const node2 = new Status.Daemon('Node2', 15000, {
>     ip: 'CONTROLLER-IP',
>     port: 'CONTROLLER-PORT'
> });
> ```
> 
> You need to put this on each separate node: [click-here](https://haste.bluefoxhost.com/ecagi.php)

Hmmm

**Comment by HirziDevs** [comment]
> It appears that you are using an outdated version of PteroStatus, please update.
> 
> Also you can't just add this to the same file:
> 
> ```js
> const node1 = new Status.Daemon('Node1', 15000, {
>     ip: 'CONTROLLER-IP',
>     port: 'CONTROLLER-PORT'
> });
> 
> const node2 = new Status.Daemon('Node2', 15000, {
>     ip: 'CONTROLLER-IP',
>     port: 'CONTROLLER-PORT'
> });
> ```
> 
> You need to put this on each separate node: [click-here](https://haste.bluefoxhost.com/ecagi.php)

thanks sorry for late reply can you post the code again? im very busy and can't reply

**Comment by FlaringPhoenix** [comment]
Add me on discord and I would love to help! FlaringPhoenix#0001
