### ISSUE TITLE
Documentation Help

### ISSUE THREAD

**Issue by SneakyHub** [FlaringPhoenix/Ptero-Status#11]
Nvm was dumb

**Comment by SneakyHub** [comment]
[DAEMON]: Failed to post stats

const Status = require('pterostatus');
const Daemon = new Status.Daemon("Node1", 15000, {
    ip: "Ip of machine",
    port: "port of wings 8080"
});

**Comment by SneakyHub** [comment]
What am I doing wrong?

**Comment by DennisFrankenhuizen** [comment]
my having the same
