### ISSUE TITLE
Unable to user [error]

### ISSUE THREAD

**Issue by Aayush-683** [FlaringPhoenix/Ptero-Status#14]
I only have 1 node and i have added both the snippets to index.js of the bot file
Im still having issues :(
```
![image](https://user-images.githubusercontent.com/75422863/118348101-4a138c80-b548-11eb-9933-bde20f79e326.png)
```

**Comment by FlaringPhoenix** [comment]
Add me on discord and I would love to help! FlaringPhoenix#0001
