### ISSUE TITLE
"Failed to post stats"

### ISSUE THREAD

**Issue by walmartbaggg** [FlaringPhoenix/Ptero-Status#18]
Hello, so I recently installed this API and I ran it. I did all of the setup but it keeps saying failed to post stats. I don't know why but please help. Thank you.

**Comment by FlaringPhoenix** [comment]
Add me on discord and I would love to help! FlaringPhoenix#0001

**Comment by anondev-sudo** [comment]
@FlaringPhoenix When?
I am looking for this too
