### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ririko5834** [FlaringPhoenix/Ptero-Status#2]
Could you please add there also total users registred count and total server's count per nodes?
You can use pterodactyl api for this? Also the RAM and storage usage should be fetched from Pterodactyl api.

**Comment by FlaringPhoenix** [comment]
I love this suggestion. I will get this done ASAP. 

Btw, you can't fetch ram and storage usage from the pterodactyl api.

**Comment by ririko5834** [comment]
Ok

> Btw, you can't fetch ram and storage usage from the pterodactyl api.

Oh, but please add total registred users stats and total servers per node stats

**Comment by ririko5834** [comment]
Btw, why PteroManager repo is not public now 😢 ? 
Please make it opensource again 🙏

**Comment by FlaringPhoenix** [comment]
> Ok
> 
> > Btw, you can't fetch ram and storage usage from the pterodactyl api.
> 
> Oh, but please add total registred users stats and total servers per node stats

Yes, I will be adding this asap. PteroManager is now opensource again

**Comment by ririko5834** [comment]
Thanks 👍, I also sent there some suggestions. There should be really commands to create, delete, suspend server for user and to get information about mention user (something like `pm!account info @mention` to get info about user's account on panel). And when PteroManager repo will be updated (I found that some commands that are in hosted version are not on Github :/)?

**Comment by FlaringPhoenix** [comment]
> Thanks 👍, I also sent there some suggestions. There should be really commands to create, delete, suspend server for user (this should be only for panel admins). And when PteroManager repo will be updated (I found that some commands that are in hosted version are not on Github :/)?

I really appreciate your suggestions. I will be working on it more tomorrow and the next day, just been busy. The reason that you don't see all of the commands on the repo is due to me not pushing the massive update to the github repo yet. I have made 120+ file changes so far.

**Comment by ririko5834** [comment]
Thanks, hope that you will push new updates soon! ❤️

**Comment by FlaringPhoenix** [comment]
> Ok
> 
> > Btw, you can't fetch ram and storage usage from the pterodactyl api.
> 
> Oh, but please add total registred users stats and total servers per node stats

Done!
